/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["_session_api_sessions__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cycles */
        get: operations["_cycles_api_sessions__sid__cycles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cycles/{pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cycle */
        get: operations["_cycle_api_cycles__pk__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perf */
        get: operations["_perf_api_sessions__sid__performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["_live_api_sessions__sid__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertInfo */
        AlertInfo: {
            /** Alert Id */
            alert_id: string;
            /** Target Price */
            target_price: number | null;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** Register Reasoning */
            register_reasoning: string | null;
        };
        /** CycleDetail */
        CycleDetail: {
            /** Id */
            id: number;
            /** Cycle Label */
            cycle_label: string;
            /** Triggered By */
            triggered_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reasoning */
            reasoning: string | null;
            /** Decision */
            decision: string | null;
            /** Trigger Context */
            trigger_context: {
                [key: string]: unknown;
            } | unknown[] | string | null;
            /** State Snapshot */
            state_snapshot: {
                [key: string]: unknown;
            } | unknown[] | string | null;
            /** Injected Events */
            injected_events: {
                [key: string]: unknown;
            } | unknown[] | string | null;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallRow"][];
            /** Tokens Consumed */
            tokens_consumed: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Cache Hit Rate */
            cache_hit_rate: number | null;
            /** Wall Time Ms */
            wall_time_ms: number | null;
            /** Llm Call Ms */
            llm_call_ms: number | null;
            /** Model Id */
            model_id: string | null;
            /** React Steps */
            react_steps?: unknown[] | {
                [key: string]: unknown;
            } | string | null;
            /** User Prompt Snapshot */
            user_prompt_snapshot?: string | null;
            /**
             * Execution Status
             * @default ok
             */
            execution_status: string;
        };
        /** CycleRow */
        CycleRow: {
            /** Id */
            id: number;
            /** Cycle Label */
            cycle_label: string;
            /** Triggered By */
            triggered_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Tokens Consumed */
            tokens_consumed: number;
            /** Wall Time Ms */
            wall_time_ms: number | null;
            /** Execution Status */
            execution_status: string;
            position: components["schemas"]["PositionBrief"] | null;
            /** Key Events */
            key_events: components["schemas"]["KeyEvent"][];
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Equity */
            equity: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KeyEvent
         * @description feed end：本轮单个关键事件。被动 fill（fill_*）+ 主动动作（open/add/close/flip/limit_order）。
         */
        KeyEvent: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Direction */
            direction: string | null;
        };
        /** LiveStatus */
        LiveStatus: {
            /** Status */
            status: string;
            /** Last Active At */
            last_active_at: string | null;
            position: components["schemas"]["PositionInfo"] | null;
            /** Open Orders */
            open_orders: components["schemas"]["OrderInfo"][];
            /** Active Alerts */
            active_alerts: components["schemas"]["AlertInfo"][];
        };
        /** OrderInfo */
        OrderInfo: {
            /** Order Id */
            order_id: string;
            /** Side */
            side: string;
            /** Order Type */
            order_type: string;
            /** Amount */
            amount: number;
            /** Trigger Price */
            trigger_price: number | null;
        };
        /**
         * Performance
         * @description 口径警示：下方标量指标为「已实现」口径（FIFO roundtrip），与 equity_curve（逐 cycle
         *     盯市、含未实现 PnL）**不同口径、不可逐点对账**。total_return_pct=gross 已实现/初始；
         *     max_drawdown_pct=net 已实现 equity 模拟。前端同台展示时须分别标注，勿让用户把曲线回撤
         *     与 max_drawdown_pct 数字对齐（设计 by-intent，见 spec §5.1 双口径）。
         */
        Performance: {
            /** Initial Balance */
            initial_balance: number;
            /** Current Position */
            current_position: string;
            /** Total Return Pct */
            total_return_pct: number;
            /** Net Pnl */
            net_pnl: number;
            /** Net Win Rate */
            net_win_rate: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Net Profit Factor */
            net_profit_factor: number | null;
            /** Total Trades */
            total_trades: number;
            /** Net Winning Trades */
            net_winning_trades: number;
            /** Net Losing Trades */
            net_losing_trades: number;
            /** Total Fees */
            total_fees: number;
            /** Equity Curve */
            equity_curve: components["schemas"]["EquityPoint"][];
            /** Trades */
            trades: components["schemas"]["TradeRow"][];
        };
        /**
         * PositionBrief
         * @description feed head：本轮开始态持仓精简（state_snapshot.position）。flat → None（不构造本模型）。
         */
        PositionBrief: {
            /** Side */
            side: string;
            /** Contracts */
            contracts: number;
            /** Entry Price */
            entry_price: number | null;
        };
        /** PositionInfo */
        PositionInfo: {
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Contracts */
            contracts: number;
            /** Entry Price */
            entry_price: number;
            /** Leverage */
            leverage: number;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
            /** Status */
            status: string;
            /** Timeframe */
            timeframe: string;
            /** Scheduler Interval Min */
            scheduler_interval_min: number;
            /** Initial Balance */
            initial_balance: number;
            /** Token Budget */
            token_budget: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Active At */
            last_active_at: string | null;
            /** System Prompt */
            system_prompt?: string | null;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Active At */
            last_active_at: string | null;
            /** Cycle Count */
            cycle_count: number;
            /** Total Return Pct */
            total_return_pct: number;
        };
        /** ToolCallRow */
        ToolCallRow: {
            /** Tool Name */
            tool_name: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number;
            /** Error Type */
            error_type: string | null;
            /** Args */
            args: {
                [key: string]: unknown;
            } | unknown[] | string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | unknown[] | string | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
        };
        /** TradeRow */
        TradeRow: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Action */
            action: string;
            /** Side */
            side: string | null;
            /** Price */
            price: number | null;
            /** Amount */
            amount: number | null;
            /** Pnl */
            pnl: number | null;
            /** Fee */
            fee: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    _session_api_sessions__sid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _cycles_api_sessions__sid__cycles_get: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number | null;
                after_id?: number | null;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _cycle_api_cycles__pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _perf_api_sessions__sid__performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Performance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _live_api_sessions__sid__live_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
